name: Votifier
main: com.vexsoftware.votifier.NuVotifierBukkit
version: maven-version-number
description: A plugin that gets notified when votes are made for the server on toplists.
authors: [blakeman8192, Kramer, tuxed]